### ISSUE TITLE
lack of education related data

### ISSUE THREAD

**Issue by mnky9800n** [learningmachineslab/tutorials#10]
all of the data thus far is just fake data generated from data generation libraries from sklearn. but i think its much more relevant to have data sets that are relevant to PER topics. This means like, a column shouldnt be `feature3` but perhaps `HSGPA` or `fci_prescore`. then there can be discussions of the analysis of this data, like, i have no idea what it means that `feature3` correlates to `feature4`, but if `HSGPA` correlates to `fci_prescore` we can think of some hypotheses as to why this is true.

**Comment by copperwire** [comment]
Closed by 0e25eef
