### ISSUE TITLE
Regression tutorial seems to be missing interpretation answers

### ISSUE THREAD

**Issue by dannycab** [learningmachineslab/tutorials#7]
Went through the regression tutorial and it appears to be focused on calculating quantities and making plots, but there are some important interpretation questions that we'd want them to reflect on that we should have answers to. 

I'll start with the first task in which the solutions show 3 different visualizations that are not interpreted (i.e., answered the posed question). These other tasks are similarly missing interpretations from the solution.

**Comment by mnky9800n** [comment]
yeah i didnt write these on purpose because i wanted to make the tutorial and get feedback on the general design prior to going all out.
